In [1]:
import numpy as np
import pandas as pd
data = pd.read_csv('gender.csv')
data.head()
df=data
y=df.iloc[:,-1]
y.head()
x=df.iloc[:, :-1]
x.head()
from sklearn.preprocessing import LabelEncoder
gender_encoder = LabelEncoder()
y= gender_encoder.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [2]:
y=df.iloc[:,-1]
y.head()

0    male
1    male
2    male
3    male
4    male
Name: label, dtype: object

In [3]:
x=df.iloc[:, :-1]
x.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm      mode  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  0.000000  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  0.000000  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  0.000000  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  0.083878  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  0.104261  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274

In [87]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.2, random_state=1)

The above steps are the same for all ML algorithms

Gaussian Naive Bayes Model without scaling and feature selection
--------------------------

In [88]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
model = GaussianNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('accuracy') 
print(metrics.accuracy_score(y_test,y_pred))

accuracy
0.869085173502


Model assumes that features/variables follow a normal distibution, hence it is the perfect condition.

Multinomial Naive Bayes Model without scaling and feature selection
----------------------------------------------------------------------

In [89]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('accuracy') 
print(metrics.accuracy_score(y_test,y_pred))

accuracy
0.507886435331


It is dicrete counts, where the model counts the number of times outcome(0/1) occurs in the document.

From the above accuracy, we identify that data has almost equal amount of males and females.

Bernoulli Naive Bayes Model without scaling and Feature selection
--

In [90]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('accuracy') 
print(metrics.accuracy_score(y_test,y_pred))

accuracy
0.501577287066


Similar to that of Multinomial NB, but instead of counting the number of times of outcomes, the model determines the outcomes occuring and the outcomes that doesnt occur.

from the above accuracy, we identify that data is equally distributed.

************Both the Multinomial and Bernoulli NB models have to be used after scaling and feature selection for a better accuracy rate.*************

Feature Importance check
-------------------------
Checking to find the important features using ensemble technique - extra trees classifier
-------------------------------------------------------------------

In [4]:
from sklearn.ensemble import ExtraTreesClassifier
fs = ExtraTreesClassifier()
fs.fit(x, y)
print(fs.feature_importances_)

[ 0.03426557  0.0388978   0.01270866  0.15732665  0.02334595  0.21423211
  0.0146471   0.01134103  0.04062753  0.02286     0.04449399  0.01975058
  0.25515593  0.01390298  0.01466318  0.0165311   0.02781432  0.01293387
  0.01340237  0.0110993 ]


Recursive Feature Elimination usign Logistic Regression
----------------------------------------------------------

In [3]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
fsmodel = LogisticRegression()
rfe = RFE(fsmodel, 1)
fit = rfe.fit(x, y)
#print("selected features: %s") % fit.support_
#print("Num features: %d") % fit.n_features_
#print ("features sorted by their rank")
#print sorted((zip(map(lambda x:round(x,4), rfe.ranking_), names)))
print(rfe.support_)
print(rfe.ranking_)

[False False False False False False False False False False False False
  True False False False False False False False]
[17  9 10  4  5  2 18 20  3 15  7 16  1 12  6 19  8 13 14 11]


Deleting the unwanted variables based on above techniques
----------

In [5]:
drop_cols = ['meanfreq','skew', 'kurt', 'meandom', 'mode', 'centroid']
x = x.drop(drop_cols, axis=1)

In [6]:
x.head()

sd    median       Q25       Q75       IQR    sp.ent       sfm  \
0  0.064241  0.032027  0.015071  0.090193  0.075122  0.893369  0.491918   
1  0.067310  0.040229  0.019414  0.092666  0.073252  0.892193  0.513724   
2  0.083829  0.036718  0.008701  0.131908  0.123207  0.846389  0.478905   
3  0.072111  0.158011  0.096582  0.207955  0.111374  0.963322  0.727232   
4  0.079146  0.124656  0.078720  0.206045  0.127325  0.971955  0.783568   

    meanfun    minfun    maxfun    mindom    maxdom   dfrange   modindx  
0  0.084279  0.015702  0.275862  0.007812  0.007812  0.000000  0.000000  
1  0.107937  0.015826  0.250000  0.007812  0.054688  0.046875  0.052632  
2  0.098706  0.015656  0.271186  0.007812  0.015625  0.007812  0.046512  
3  0.088965  0.017798  0.250000  0.007812  0.562500  0.554688  0.247119  
4  0.106398  0.016931  0.266667  0.007812  5.484375  5.476562  0.208274

Scaling
--------

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)

Split Train and Test
-------

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.2, random_state=1)

GaussianNB, MultinomialNB, BernoulliNB models Accuracy after scaling and feature prediction
----------------

In [9]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
model = GaussianNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('accuracy') 
print(metrics.accuracy_score(y_test,y_pred))

accuracy
0.929022082019


In [10]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('accuracy') 
print(metrics.accuracy_score(y_test,y_pred))

ValueError: Input X must be non-negative

In [11]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('accuracy') 
print(metrics.accuracy_score(y_test,y_pred))

accuracy
0.881703470032


After scaling and feature selection we have identified that there is a phenomenal increase in bernoulliNB and an average increase with GaussianNB.

But Gaussian Naive Bayes classifier is the best in this scenario, because it assumes that the variables are distributed normally.

We can increase the output accuracy by using cross validation as well.

Using Principal Component Analysis for dimensionality reduction
------------------------------------------------------------------

In [12]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
fit = pca.fit(x)
print(pca.explained_variance_ratio_)
print(pca.components_)
x_train_pca = pca.transform(x_train)
x_test_pca = pca.transform(x_test)
print(x_train.shape)
print(x_test.shape)

x_train_pca

[ 0.44180592]
[[-0.35152114  0.31657721  0.36617303  0.18842156 -0.31253143 -0.31210664
  -0.35196849  0.246888    0.18894617  0.13577915  0.11686874  0.26985291
   0.26783698 -0.11980087]]
(2534, 14)
(634, 14)


array([[ 3.24740614],
       [-2.019474  ],
       [ 1.57827582],
       ..., 
       [ 0.24026265],
       [-3.60507193],
       [ 0.81481967]])

GaussianNB, MultinomialNB, BernoulliNB models Accuracy after Principal Component Analysis
----------------

In [13]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
model = GaussianNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('accuracy') 
print(metrics.accuracy_score(y_test,y_pred))

accuracy
0.929022082019


In [14]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('accuracy') 
print(metrics.accuracy_score(y_test,y_pred))

ValueError: Input X must be non-negative

In [15]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('accuracy') 
print(metrics.accuracy_score(y_test,y_pred))

accuracy
0.881703470032


After PCA the accuracy does not change, i have taken my PCA output to be 1 dimensional, therfore when my one feature predicts that same accuracy when compared with all the features combined, then there is a win- win situation and the model is accurate.